ALTER TABLE update_events
    DROP CONSTRAINT IF EXISTS ck_update_events_type;

ALTER TABLE update_events
    ADD CONSTRAINT ck_update_events_type CHECK (
        event_type IN (
            'AUTHORIZED', 'DOWNLOAD_STARTED', 'DOWNLOAD_COMPLETED',
            'CHECKSUM_VALIDATED', 'SIGNATURE_VALIDATED', 'SIGNATURE_VALIDATION_FAILED',
            'POS_ACTIVITY_DETECTED', 'USER_WARNING_SENT', 'POS_CLOSED',
            'BACKUP_CREATED', 'UPDATE_STARTED', 'UPDATE_COMPLETED',
            'UPDATE_FAILED', 'VALIDATION_OK', 'VALIDATION_FAILED', 'ROLLBACK_STARTED',
            'ROLLBACK_COMPLETED', 'ROLLBACK_FAILED', 'FAILED'
        )
    );
